const GAME_DATA = {
    "Infantil": [
        { word: "Bob Esponja", hint1: "trabaja en algo que todos comen pero nadie cuestiona", hint2: "estrella" },
        { word: "Dinosaurio", hint1: "nadie los vio pero todos saben cómo eran", hint2: "extintos" },
        { word: "Helado", hint1: "desaparece más rápido cuando hace más calor", hint2: "frío" },
        { word: "Bicicleta", hint1: "al principio duele más el suelo que el intento", hint2: "equilibrio" },
        { word: "Payaso", hint1: "su trabajo es reír aunque no quiera", hint2: "circo" },
        { word: "Cohete", hint1: "todo empieza con una cuenta regresiva", hint2: "espacio" },
        { word: "Arcoíris", hint1: "nadie puede tocarlo pero todos lo han visto", hint2: "colores" },
        { word: "Piñata", hint1: "la gracia es no ver lo que haces", hint2: "dulces" },
        { word: "Superhéroe", hint1: "nadie sospecha de él en su vida normal", hint2: "identidad" },
        { word: "Dragón", hint1: "a veces protege lo que otros quieren robar", hint2: "fuego" },
        { word: "Princesa", hint1: "su historia depende de quién la rescata", hint2: "castillo" },
        { word: "Robot", hint1: "hace todo bien menos sentir", hint2: "metal" },
        { word: "Globo", hint1: "sube hasta que alguien lo pierde", hint2: "aire" },
        { word: "Magia", hint1: "solo funciona si crees un poco", hint2: "truco" },
        { word: "Tren", hint1: "no puede girar aunque quiera", hint2: "rieles" },
        { word: "Sirena", hint1: "no pertenece ni a un lado ni al otro", hint2: "mar" },
        { word: "Castillo", hint1: "defiende más de lo que protege", hint2: "rey" },
        { word: "Duende", hint1: "aparece cuando nadie está mirando", hint2: "verde" },
        { word: "Huevo Kinder", hint1: "importa más lo de dentro que lo de fuera", hint2: "sorpresa" },
        { word: "Patineta", hint1: "una caída enseña más que mil intentos", hint2: "ruedas" },
        { word: "Cometa", hint1: "vuela solo si alguien lo controla", hint2: "cuerda" },
        { word: "Tambor", hint1: "mientras más fuerte, mejor suena", hint2: "ritmo" },
        { word: "Rompecabezas", hint1: "siempre falta una pieza hasta el final", hint2: "piezas" },
        { word: "Lego", hint1: "todo depende de tu imaginación", hint2: "bloques" },
        { word: "Tobogán", hint1: "subir es aburrido, bajar es divertido", hint2: "parque" },
        { word: "Pelota", hint1: "siempre regresa si la sueltas", hint2: "rebote" },
        { word: "Muñeco", hint1: "no habla pero todos le hablan", hint2: "juguete" },
        { word: "Caramelo", hint1: "dura poco pero se recuerda", hint2: "dulce" },
        { word: "Espada de juguete", hint1: "nadie sale herido pero todos luchan", hint2: "batalla" },
        { word: "Máscara", hint1: "eres otro mientras la usas", hint2: "ocultar" },
        { word: "Escuela", hint1: "vas sin querer pero luego la recuerdas", hint2: "clases" },
        { word: "Recreo", hint1: "el mejor momento del día sin aprender nada", hint2: "descanso" },
        { word: "Maestro", hint1: "sabe más de lo que parece", hint2: "enseñar" },
        { word: "Columpio", hint1: "vas y vuelves sin avanzar", hint2: "balanceo" },
        { word: "Arena", hint1: "construyes algo que no durará", hint2: "playa" },
        { word: "Castillo de arena", hint1: "el mar siempre gana al final", hint2: "olas" },
        { word: "Disfraz", hint1: "no eres tú pero actúas como si lo fueras", hint2: "fiesta" },
        { word: "Chocolate", hint1: "derrite decisiones", hint2: "cacao" },
        { word: "Burbujas", hint1: "existen solo un segundo", hint2: "aire" },
        { word: "Cuento", hint1: "todo empieza con algo que no pasó", hint2: "historia" },
        { word: "Dragón de papel", hint1: "no quema pero vuela", hint2: "manualidad" },
        { word: "Tiza", hint1: "desaparece mientras enseña", hint2: "pizarra" },
        { word: "Colores", hint1: "sin ellos todo sería lo mismo", hint2: "dibujar" },
        { word: "Dibujo", hint1: "vale más la idea que el resultado", hint2: "arte" },
        { word: "Canción infantil", hint1: "no la olvidas aunque quieras", hint2: "repetir" },
        { word: "Cama elástica", hint1: "la gravedad es solo una sugerencia", hint2: "saltar" },
        { word: "Masa de moldear", hint1: "todos los colores terminan en marrón", hint2: "plastilina" },
        { word: "Escondidas", hint1: "el silencio es tu mejor aliado", hint2: "buscar" },
        { word: "Zapatos con luces", hint1: "correr no te hace más rápido, pero se ve mejor", hint2: "brillar" },
        { word: "Triciclo", hint1: "la versión segura pero aburrida de lo que quieres", hint2: "pedales" }
    ],
    "Peliculas": [
        { word: "Harry Potter", hint1: "empieza en un lugar donde no pertenece", hint2: "magia" },
        { word: "Titanic", hint1: "lo más valioso termina perdido", hint2: "barco" },
        { word: "Matrix", hint1: "la realidad depende de una elección", hint2: "roja" },
        { word: "Joker", hint1: "la risa no siempre es alegría", hint2: "caos" },
        { word: "Coco", hint1: "morir no es el final si alguien te recuerda", hint2: "ofrenda" },
        { word: "Shrek", hint1: "no todo monstruo es villano", hint2: "pantano" },
        { word: "Avengers", hint1: "perder también puede ser parte del plan", hint2: "guante" },
        { word: "Inception", hint1: "soñar dentro de otro sueño", hint2: "trompo" },
        { word: "Frozen", hint1: "no todos los actos de amor son románticos", hint2: "hielo" },
        { word: "Toy Story", hint1: "nadie los ve cuando son ellos mismos", hint2: "juguetes" },
        { word: "Interstellar", hint1: "el tiempo no es igual para todos", hint2: "espacio" },
        { word: "El Padrino", hint1: "una oferta que no puedes rechazar", hint2: "familia" },
        { word: "Gladiador", hint1: "lo perdió todo antes de ganar respeto", hint2: "arena" },
        { word: "Jurassic Park", hint1: "revivir algo no significa controlarlo", hint2: "ADN" },
        { word: "Avatar", hint1: "otro cuerpo, otra vida", hint2: "azul" },
        { word: "El Rey León", hint1: "huir no evita el destino", hint2: "rey" },
        { word: "Batman", hint1: "el miedo es su herramienta", hint2: "murciélago" },
        { word: "Spider-Man", hint1: "todo cambia por un accidente", hint2: "araña" },
        { word: "Deadpool", hint1: "sabe que todo es un juego", hint2: "romper" },
        { word: "Iron Man", hint1: "su prisión fue su inicio", hint2: "armadura" },
        { word: "Thor", hint1: "pierde todo antes de entender su poder", hint2: "trueno" },
        { word: "Doctor Strange", hint1: "romperse fue necesario", hint2: "tiempo" },
        { word: "Hulk", hint1: "no siempre puedes controlar lo que eres", hint2: "ira" },
        { word: "Black Panther", hint1: "ocultar es proteger", hint2: "vibranium" },
        { word: "Captain America", hint1: "pertenece a otro tiempo", hint2: "escudo" },
        { word: "Fast & Furious", hint1: "la familia importa más que la ley", hint2: "autos" },
        { word: "John Wick", hint1: "todo empezó por algo pequeño", hint2: "venganza" },
        { word: "Rocky", hint1: "no se trata de ganar", hint2: "boxeo" },
        { word: "Rambo", hint1: "la guerra no termina", hint2: "soldado" },
        { word: "The Matrix Reloaded", hint1: "la elección sigue siendo una ilusión", hint2: "neo" },
        { word: "Up", hint1: "viajar sin moverte", hint2: "globos" },
        { word: "Wall-E", hint1: "el último haciendo lo mismo", hint2: "basura" },
        { word: "Finding Nemo", hint1: "perder obliga a buscar", hint2: "océano" },
        { word: "Cars", hint1: "perder te enseña más que ganar", hint2: "carrera" },
        { word: "Monsters Inc", hint1: "lo que asusta también trabaja", hint2: "puertas" },
        { word: "Inside Out", hint1: "no todas las emociones quieren lo mismo", hint2: "mente" },
        { word: "Soul", hint1: "vivir no es solo existir", hint2: "jazz" },
        { word: "Encanto", hint1: "no tener poder también es uno", hint2: "familia" },
        { word: "Moana", hint1: "el mar decide más que tú", hint2: "isla" },
        { word: "Aladdin", hint1: "tenerlo todo no cambia quién eres", hint2: "lámpara" },
        { word: "Hércules", hint1: "ser fuerte no te hace héroe", hint2: "dioses" },
        { word: "Tarzan", hint1: "no pertenece a donde creció", hint2: "selva" },
        { word: "Frozen 2", hint1: "respuestas en el pasado", hint2: "bosque" },
        { word: "Shrek 2", hint1: "cambiar por amor no siempre funciona", hint2: "poción" },
        { word: "Toy Story 3", hint1: "dejar ir también es amor", hint2: "adiós" },
        { word: "El Señor de los Anillos", hint1: "el viaje más largo por una joya defectuosa", hint2: "anillo" },
        { word: "Star Wars", hint1: "problemas familiares a escala galáctica", hint2: "fuerza" },
        { word: "El resplandor", hint1: "demasiado trabajo y poco juego no terminan bien", hint2: "hacha" },
        { word: "Pulp Fiction", hint1: "el tiempo no importa si la historia es buena", hint2: "maletín" },
        { word: "El club de la pelea", hint1: "la regla principal es no hablar", hint2: "golpes" }
    ],
    "Objetos": [
        { word: "Tijeras", hint1: "solo funcionan cuando dejan de ser una", hint2: "cortar" },
        { word: "Termómetro", hint1: "su valor cambia sin moverse", hint2: "temperatura" },
        { word: "Brújula", hint1: "ignora todo excepto una cosa invisible", hint2: "norte" },
        { word: "Linterna", hint1: "solo importa cuando todo lo demás falla", hint2: "luz" },
        { word: "Paraguas", hint1: "aparece tarde y desaparece antes", hint2: "lluvia" },
        { word: "Calculadora", hint1: "confías en ella incluso cuando no entiendes el resultado", hint2: "números" },
        { word: "Candado", hint1: "protege incluso de su dueño", hint2: "clave" },
        { word: "Reloj de arena", hint1: "su función es terminarse", hint2: "tiempo" },
        { word: "Mochila", hint1: "carga más de lo que aparenta", hint2: "espalda" },
        { word: "Espejo", hint1: "nunca te muestra como otros te ven", hint2: "reflejo" },
        { word: "Ventilador", hint1: "mueve lo mismo sin cambiarlo", hint2: "aire" },
        { word: "Microscopio", hint1: "agranda lo que nadie nota", hint2: "lentes" },
        { word: "Guitarra", hint1: "suena mejor cuanto más duele al inicio", hint2: "cuerdas" },
        { word: "Llave", hint1: "pequeña pero decide acceso", hint2: "cerradura" },
        { word: "Puerta", hint1: "define si estás dentro o fuera", hint2: "entrada" },
        { word: "Ventana", hint1: "te conecta sin dejarte pasar", hint2: "vista" },
        { word: "Silla", hint1: "no sirve si no te detienes", hint2: "sentarse" },
        { word: "Mesa", hint1: "todo pasa encima de ella", hint2: "superficie" },
        { word: "Cuchillo", hint1: "útil o peligroso según quién lo use", hint2: "filo" },
        { word: "Tenedor", hint1: "divide para poder usar", hint2: "pinchos" },
        { word: "Cuchara", hint1: "recoge sin cortar", hint2: "sopa" },
        { word: "Plato", hint1: "importa más lo que lleva que él mismo", hint2: "comida" },
        { word: "Vaso", hint1: "puede estar lleno o vacío y decir mucho", hint2: "líquido" },
        { word: "Botella", hint1: "guarda hasta que decides abrir", hint2: "tapa" },
        { word: "Lapicero", hint1: "desaparece lo que lleva dentro", hint2: "tinta" },
        { word: "Lápiz", hint1: "cada error lo hace más pequeño", hint2: "grafito" },
        { word: "Borrador", hint1: "existe para eliminar lo que ya hiciste", hint2: "error" },
        { word: "Regla", hint1: "sirve para lo recto pero no lo crea", hint2: "medir" },
        { word: "Cuaderno", hint1: "empieza vacío y termina olvidado", hint2: "hojas" },
        { word: "Libro", hint1: "te lleva lejos sin moverte", hint2: "leer" },
        { word: "Teléfono", hint1: "te acerca a quien no está", hint2: "llamada" },
        { word: "Computadora", hint1: "sabe todo pero depende de ti", hint2: "pantalla" },
        { word: "Mouse", hint1: "se mueve para que otro lo haga", hint2: "cursor" },
        { word: "Teclado", hint1: "traduce pensamientos en símbolos", hint2: "teclas" },
        { word: "Audífonos", hint1: "te aíslan sin moverte", hint2: "sonido" },
        { word: "Televisor", hint1: "muestra mundos que no existen", hint2: "pantalla" },
        { word: "Control remoto", hint1: "manda sin tocar", hint2: "botones" },
        { word: "Enchufe", hint1: "sin él nada empieza", hint2: "energía" },
        { word: "Cable", hint1: "conecta pero estorba", hint2: "corriente" },
        { word: "Batería", hint1: "muere lentamente mientras la usas", hint2: "carga" },
        { word: "Reloj", hint1: "nunca se detiene aunque quieras", hint2: "hora" },
        { word: "Calendario", hint1: "organiza lo que no controlas", hint2: "fechas" },
        { word: "Lámpara", hint1: "solo importa en ausencia", hint2: "luz" },
        { word: "Interruptor", hint1: "todo depende de una decisión mínima", hint2: "encender" },
        { word: "Cámara", hint1: "congela algo que ya pasó", hint2: "foto" },
        { word: "Maleta", hint1: "lleva lo necesario y lo innecesario", hint2: "viaje" },
        { word: "Ropa", hint1: "dice más de ti que tus palabras", hint2: "vestir" },
        { word: "Zapatos", hint1: "te acompañan a todos lados pero nunca avanzan solos", hint2: "caminar" },
        { word: "Sombrero", hint1: "no cambia quién eres pero sí cómo te ven", hint2: "cabeza" },
        { word: "Lentes", hint1: "corrigen sin cambiar la realidad", hint2: "visión" }
    ],
    "Lugares": [
        { word: "Aeropuerto", hint1: "las despedidas duran más que los viajes", hint2: "vuelos" },
        { word: "Mazmorra", hint1: "no entras por voluntad propia", hint2: "encierro" },
        { word: "Faro", hint1: "su función es evitar finales", hint2: "luz" },
        { word: "Casino", hint1: "ganar es solo una ilusión temporal", hint2: "azar" },
        { word: "Iglesia", hint1: "muchos hablan sin esperar respuesta", hint2: "fe" },
        { word: "Zoológico", hint1: "la libertad depende del lado en que estés", hint2: "jaulas" },
        { word: "Submarino", hint1: "un error no deja segunda opción", hint2: "profundidad" },
        { word: "Estación espacial", hint1: "caer es imposible pero flotar no es libertad", hint2: "órbita" },
        { word: "Biblioteca", hint1: "el ruido molesta más que en cualquier otro lugar", hint2: "libros" },
        { word: "Cárcel", hint1: "el tiempo pesa más aquí", hint2: "rejas" },
        { word: "Volcán", hint1: "guarda algo que tarde o temprano sale", hint2: "lava" },
        { word: "Selva", hint1: "nunca está realmente en silencio", hint2: "vegetación" },
        { word: "Cementerio", hint1: "los visitantes hablan más que los residentes", hint2: "tumbas" },
        { word: "Estadio", hint1: "miles sienten lo mismo al mismo tiempo", hint2: "gradas" },
        { word: "Hospital", hint1: "unos entran por miedo, otros por esperanza", hint2: "pacientes" },
        { word: "Escuela", hint1: "vas sin querer pero te marca años", hint2: "clases" },
        { word: "Universidad", hint1: "nadie te obliga pero igual te pesa", hint2: "carrera" },
        { word: "Oficina", hint1: "el tiempo pasa más lento de lo normal", hint2: "trabajo" },
        { word: "Casa", hint1: "no siempre es donde naciste", hint2: "hogar" },
        { word: "Hotel", hint1: "duermes donde no perteneces", hint2: "estancia" },
        { word: "Restaurante", hint1: "pagas más por la experiencia que por la comida", hint2: "menú" },
        { word: "Cocina", hint1: "todo empieza aquí pero nadie se queda", hint2: "preparar" },
        { word: "Baño", hint1: "es privado incluso en público", hint2: "higiene" },
        { word: "Dormitorio", hint1: "es donde más vulnerable eres", hint2: "dormir" },
        { word: "Sala", hint1: "todo pasa ahí pero nada empieza ahí", hint2: "visitas" },
        { word: "Calle", hint1: "todos pasan pero nadie se queda", hint2: "tránsito" },
        { word: "Puente", hint1: "existe solo para conectar", hint2: "cruzar" },
        { word: "Túnel", hint1: "avanzas sin ver el final", hint2: "oscuridad" },
        { word: "Parque", hint1: "parece tranquilo pero siempre hay movimiento", hint2: "verde" },
        { word: "Playa", hint1: "el final de algo que nunca se detiene", hint2: "arena" },
        { word: "Desierto", hint1: "todo sobra excepto lo esencial", hint2: "arena" },
        { word: "Montaña", hint1: "subir es opcional, bajar obligatorio", hint2: "altura" },
        { word: "Bosque", hint1: "puedes perderte sin darte cuenta", hint2: "árboles" },
        { word: "Isla", hint1: "todo termina en lo mismo", hint2: "rodeado" },
        { word: "Océano", hint1: "lo más profundo sigue sin conocerse", hint2: "agua" },
        { word: "Cueva", hint1: "el pasado se queda atrapado ahí", hint2: "roca" },
        { word: "Templo", hint1: "no importa la religión, el respeto es el mismo", hint2: "ritual" },
        { word: "Mercado", hint1: "el precio nunca es el primero que escuchas", hint2: "negociar" },
        { word: "Supermercado", hint1: "compras más de lo que planeas", hint2: "carrito" },
        { word: "Banco", hint1: "guardas algo que no ves", hint2: "dinero" },
        { word: "Tribunal", hint1: "ganar no siempre significa tener razón", hint2: "juicio" },
        { word: "Comisaría", hint1: "entras voluntariamente o no", hint2: "policía" },
        { word: "Gimnasio", hint1: "vas a sufrir por decisión propia", hint2: "ejercicio" },
        { word: "Discoteca", hint1: "nadie habla pero todos se entienden", hint2: "baile" },
        { word: "Bar", hint1: "las decisiones empeoran con el tiempo", hint2: "bebidas" },
        { word: "Teatro", hint1: "todo es mentira pero se siente real", hint2: "escenario" },
        { word: "Cine", hint1: "dos horas viviendo otra vida", hint2: "película" },
        { word: "Museo", hint1: "el pasado se vuelve intocable", hint2: "historia" },
        { word: "Galería", hint1: "mirar es más importante que entender", hint2: "arte" },
        { word: "Estación de tren", hint1: "todo es espera o despedida", hint2: "andén" }
    ],
    "Adultos": [
        { word: "Infidelidad", hint1: "todo cambia con un mensaje que no debía llegar", hint2: "engaño" },
        { word: "Tinder", hint1: "decides en segundos algo que puede durar horas", hint2: "match" },
        { word: "Cita a ciegas", hint1: "todo depende de la primera impresión", hint2: "desconocido" },
        { word: "Resaca", hint1: "prometes no repetirlo… hasta la siguiente vez", hint2: "alcohol" },
        { word: "Celos", hint1: "no necesitas pruebas para sentirlos", hint2: "inseguridad" },
        { word: "Deseo", hint1: "aparece sin pedir permiso", hint2: "impulso" },
        { word: "Atracción", hint1: "no sabes por qué, pero pasa", hint2: "química" },
        { word: "Coqueteo", hint1: "todo se dice sin decirlo", hint2: "miradas" },
        { word: "Seductor", hint1: "juega mejor con palabras que con hechos", hint2: "encanto" },
        { word: "Tentación", hint1: "sabes que no deberías… pero igual", hint2: "prohibido" },
        { word: "Amante", hint1: "existe en secreto pero pesa mucho", hint2: "oculto" },
        { word: "Aventura", hint1: "empieza sin planes y termina mal", hint2: "ocasional" },
        { word: "Desliz", hint1: "un segundo que cambia todo", hint2: "error" },
        { word: "Noche loca", hint1: "al día siguiente faltan piezas", hint2: "exceso" },
        { word: "Mirada incómoda", hint1: "dura más de lo necesario", hint2: "intención" },
        { word: "Hotel", hint1: "nadie pregunta y eso es parte del trato", hint2: "habitación" },
        { word: "Secreto", hint1: "cuesta más guardarlo que decirlo", hint2: "oculto" },
        { word: "Mentira", hint1: "funciona hasta que deja de hacerlo", hint2: "historia" },
        { word: "Excusa", hint1: "suena bien hasta que preguntas más", hint2: "justificación" },
        { word: "Mensaje borrado", hint1: "dice más que si estuviera ahí", hint2: "chat" },
        { word: "Foto comprometedora", hint1: "no debería existir pero existe", hint2: "prueba" },
        { word: "Alcohol", hint1: "reduce decisiones y aumenta errores", hint2: "bebida" },
        { word: "Discoteca", hint1: "nadie escucha pero todos entienden", hint2: "baile" },
        { word: "Baile pegado", hint1: "no es necesario pero igual pasa", hint2: "cerca" },
        { word: "Silencio incómodo", hint1: "dice más que cualquier palabra", hint2: "tensión" },
        { word: "Relación tóxica", hint1: "sabes que está mal pero sigues", hint2: "dependencia" },
        { word: "Manipulación", hint1: "te convence de algo que no querías", hint2: "control" },
        { word: "Control", hint1: "empieza sutil y termina evidente", hint2: "dominio" },
        { word: "Dominación", hint1: "uno decide más que el otro", hint2: "poder" },
        { word: "Sumisión", hint1: "ceder también es una decisión", hint2: "ceder" },
        { word: "Prohibido", hint1: "eso es justamente lo que lo hace atractivo", hint2: "límite" },
        { word: "Riesgo", hint1: "sin él no sería tan interesante", hint2: "peligro" },
        { word: "Adicción", hint1: "sabes que te hace mal pero vuelves", hint2: "dependencia" },
        { word: "Obsesión", hint1: "piensas más de lo que deberías", hint2: "exceso" },
        { word: "Fantasía", hint1: "mejor en la mente que en la realidad", hint2: "imaginación" },
        { word: "Provocación", hint1: "no es directo pero se entiende", hint2: "intención" },
        { word: "Indirecta", hint1: "si la entiendes, cambia todo", hint2: "mensaje" },
        { word: "Tensión", hint1: "algo está por pasar pero no pasa", hint2: "ambiente" },
        { word: "Atracción prohibida", hint1: "justamente no debería pasar", hint2: "límite" },
        { word: "Error", hint1: "no parecía grave en el momento", hint2: "decisión" },
        { word: "Arrepentimiento", hint1: "llega siempre después", hint2: "culpa" },
        { word: "Excitación", hint1: "el cuerpo decide antes que tú", hint2: "reacción" },
        { word: "Impulso", hint1: "no pasa por la razón", hint2: "instinto" },
        { word: "Instinto", hint1: "no se aprende, se siente", hint2: "natural" },
        { word: "Tentación mutua", hint1: "ambos saben pero nadie lo dice", hint2: "complicidad" },
        { word: "Juego de rol", hint1: "fingir ser otro a veces revela quién eres", hint2: "actuar" },
        { word: "Mensaje de madrugada", hint1: "nunca trae buenas intenciones ni buenas decisiones", hint2: "hora" },
        { word: "Ex", hint1: "el pasado que siempre amenaza con volver", hint2: "pasado" },
        { word: "Impuestos", hint1: "el dolor más constante de crecer", hint2: "pagar" },
        { word: "Café", hint1: "sin él, la mañana es un mito", hint2: "despierto" }
    ],
    "Picante": [
        { word: "Mirada fija", hint1: "dura más de lo socialmente aceptable", hint2: "intención" },
        { word: "Silencio tenso", hint1: "nadie habla porque ambos entienden", hint2: "pausa" },
        { word: "Proximidad", hint1: "no hay contacto… pero casi", hint2: "cerca" },
        { word: "Respiración", hint1: "cambia sin razón aparente", hint2: "ritmo" },
        { word: "Contacto accidental", hint1: "no fue planeado… pero no se retira", hint2: "roce" },
        { word: "Juego peligroso", hint1: "empieza como broma y escala rápido", hint2: "riesgo" },
        { word: "Confianza", hint1: "sin ella nada de esto pasaría", hint2: "límite" },
        { word: "Límite", hint1: "cruzarlo cambia todo", hint2: "borde" },
        { word: "Tensión acumulada", hint1: "no explota… todavía", hint2: "espera" },
        { word: "Mirada cómplice", hint1: "solo dos personas entienden", hint2: "secreto" },
        { word: "Doble sentido", hint1: "depende de quién lo escuche", hint2: "interpretar" },
        { word: "Indirecta pesada", hint1: "ya no es tan indirecta", hint2: "mensaje" },
        { word: "Provocación sutil", hint1: "no es directa pero funciona", hint2: "gesto" },
        { word: "Sonrisa sospechosa", hint1: "no es inocente", hint2: "expresión" },
        { word: "Juego de miradas", hint1: "nadie más lo nota", hint2: "contacto" },
        { word: "Espacio personal", hint1: "deja de existir poco a poco", hint2: "distancia" },
        { word: "Momento incómodo", hint1: "nadie quiere moverse primero", hint2: "quietud" },
        { word: "Ambiente cargado", hint1: "algo se siente en el aire", hint2: "tensión" },
        { word: "Expectativa", hint1: "lo que viene importa más que lo que pasa", hint2: "anticipación" },
        { word: "Control perdido", hint1: "ya no decides completamente", hint2: "impulso" },
        { word: "Impulso", hint1: "aparece antes que la razón", hint2: "instinto" },
        { word: "Instinto", hint1: "no pide permiso", hint2: "natural" },
        { word: "Deseo contenido", hint1: "está ahí pero no sale", hint2: "reprimir" },
        { word: "Atracción mutua", hint1: "ninguno lo dice, ambos lo saben", hint2: "química" },
        { word: "Complicidad", hint1: "sin palabras ya hay acuerdo", hint2: "entender" },
        { word: "Secreto compartido", hint1: "los une más de lo que deberían", hint2: "oculto" },
        { word: "Situación inapropiada", hint1: "no es el lugar correcto", hint2: "contexto" },
        { word: "Riesgo innecesario", hint1: "justamente por eso ocurre", hint2: "peligro" },
        { word: "Decisión impulsiva", hint1: "no se piensa, se hace", hint2: "momento" },
        { word: "Consecuencia", hint1: "siempre llega después", hint2: "resultado" },
        { word: "Arrepentimiento", hint1: "no existía hace unos minutos", hint2: "culpa" },
        { word: "Excusa débil", hint1: "ni quien la dice la cree", hint2: "justificar" },
        { word: "Mensaje tarde", hint1: "llega cuando ya es complicado", hint2: "hora" },
        { word: "Notificación", hint1: "puede arruinar todo en segundos", hint2: "celular" },
        { word: "Pantalla bloqueada", hint1: "esconde más de lo que muestra", hint2: "secreto" },
        { word: "Distancia corta", hint1: "un paso lo cambia todo", hint2: "cerca" },
        { word: "Movimiento lento", hint1: "se siente más de lo que se ve", hint2: "ritmo" },
        { word: "Tiempo detenido", hint1: "parece que nada más importa", hint2: "instante" },
        { word: "Interrupción", hint1: "llega en el peor momento", hint2: "corte" },
        { word: "Oportunidad", hint1: "dura menos de lo que quisieras", hint2: "instante" },
        { word: "Juego mental", hint1: "todo pasa en la cabeza primero", hint2: "pensar" },
        { word: "Fantasía", hint1: "funciona mejor ahí que en realidad", hint2: "imaginar" },
        { word: "Imaginación", hint1: "completa lo que no pasa", hint2: "mente" },
        { word: "Tensión resuelta", hint1: "después ya nada es igual", hint2: "cambio" },
        { word: "Ambigüedad", hint1: "puede significar muchas cosas", hint2: "duda" },
        { word: "Situación límite", hint1: "un paso más y no hay vuelta atrás", hint2: "decisión" },
        { word: "Punto de quiebre", hint1: "todo cambia en un instante", hint2: "ruptura" },
        { word: "Atracción prohibida", hint1: "no debería… pero está", hint2: "límite" },
        { word: "Mirada final", hint1: "dice más que todo lo anterior", hint2: "cierre" },
        { word: "Silencio después", hint1: "más fuerte que cualquier palabra", hint2: "vacío" }
    ],
    "Profesiones": [
        { word: "Abogado", hint1: "convierte problemas en argumentos", hint2: "defensa" },
        { word: "Médico", hint1: "toma decisiones cuando otros dudan", hint2: "salud" },
        { word: "Ingeniero", hint1: "hace que las ideas no se caigan", hint2: "estructura" },
        { word: "Arquitecto", hint1: "imagina espacios antes de que existan", hint2: "diseño" },
        { word: "Psicólogo", hint1: "escucha más de lo que responde", hint2: "mente" },
        { word: "Profesor", hint1: "repite hasta que alguien entienda", hint2: "enseñar" },
        { word: "Chef", hint1: "mezcla todo… pero con intención", hint2: "cocina" },
        { word: "Policía", hint1: "interviene cuando alguien cruza la línea", hint2: "orden" },
        { word: "Bombero", hint1: "entra cuando todos salen", hint2: "fuego" },
        { word: "Periodista", hint1: "pregunta lo que otros evitan", hint2: "noticia" },
        { word: "Actor", hint1: "vive vidas que no le pertenecen", hint2: "escena" },
        { word: "Cantante", hint1: "dice mucho sin hablar", hint2: "voz" },
        { word: "Programador", hint1: "arregla cosas que otros no ven", hint2: "código" },
        { word: "Diseñador gráfico", hint1: "hace visible lo que no lo es", hint2: "visual" },
        { word: "Fotógrafo", hint1: "detiene momentos sin tocarlos", hint2: "imagen" },
        { word: "Dentista", hint1: "trabaja donde pocos quieren mirar", hint2: "boca" },
        { word: "Veterinario", hint1: "cura sin recibir palabras", hint2: "animal" },
        { word: "Contador", hint1: "todo debe cuadrar, siempre", hint2: "números" },
        { word: "Economista", hint1: "explica lo que nadie entiende del dinero", hint2: "mercado" },
        { word: "Piloto", hint1: "controla sin tocar el suelo", hint2: "vuelo" },
        { word: "Azafata", hint1: "mantiene la calma a miles de metros", hint2: "cabina" },
        { word: "Taxista", hint1: "sabe más rutas que historias", hint2: "transporte" },
        { word: "Electricista", hint1: "si falla, todo se apaga", hint2: "energía" },
        { word: "Mecánico", hint1: "entiende ruidos que otros ignoran", hint2: "motor" },
        { word: "Carpintero", hint1: "da forma a lo rígido", hint2: "madera" },
        { word: "Albañil", hint1: "construye desde lo básico", hint2: "obra" },
        { word: "Guardia de seguridad", hint1: "observa sin ser notado", hint2: "vigilar" },
        { word: "Actor de doblaje", hint1: "da voz sin aparecer", hint2: "voz" },
        { word: "Influencer", hint1: "convierte atención en valor", hint2: "redes" },
        { word: "Youtuber", hint1: "vive de ser visto", hint2: "videos" },
        { word: "Streamer", hint1: "todo pasa en tiempo real", hint2: "directo" },
        { word: "Community manager", hint1: "responde por otros", hint2: "marca" },
        { word: "Publicista", hint1: "hace que lo innecesario parezca urgente", hint2: "venta" },
        { word: "Vendedor", hint1: "te convence sin obligarte", hint2: "oferta" },
        { word: "Recepcionista", hint1: "es el primer filtro", hint2: "entrada" },
        { word: "Secretaria", hint1: "organiza lo que otros desordenan", hint2: "agenda" },
        { word: "Traductor", hint1: "dice lo mismo de otra forma", hint2: "idioma" },
        { word: "Guía turístico", hint1: "conoce historias mejor que lugares", hint2: "recorrido" },
        { word: "Historiador", hint1: "vive en lo que ya pasó", hint2: "pasado" },
        { word: "Científico", hint1: "duda de todo… incluso de sí mismo", hint2: "experimento" },
        { word: "Químico", hint1: "mezcla sin margen de error", hint2: "reacción" },
        { word: "Farmacéutico", hint1: "entrega soluciones con medida exacta", hint2: "medicina" },
        { word: "Enfermero", hint1: "está cuando más se necesita", hint2: "cuidado" },
        { word: "Terapeuta", hint1: "te hace decir lo que evitas", hint2: "emociones" },
        { word: "Entrenador", hint1: "te exige más de lo que quieres", hint2: "físico" },
        { word: "Nutricionista", hint1: "decide qué entra y qué no", hint2: "dieta" },
        { word: "Barbero", hint1: "cambia sin alterar demasiado", hint2: "cabello" },
        { word: "Estilista", hint1: "define cómo te ven los demás", hint2: "imagen" },
        { word: "Actor de cine para adultos", hint1: "trabaja donde todo es observado", hint2: "cámara" },
        { word: "Stripper", hint1: "cobra por mantener atención", hint2: "escena" }
    ],
    "Cuerpo": [
        { word: "cabeza", hint1: "Donde empiezan muchas decisiones… y terminan algunas", hint2: "cima" },
        { word: "ojo", hint1: "Puede traicionarte sin decir una palabra", hint2: "mirada" },
        { word: "nariz", hint1: "A veces detecta problemas antes que tú", hint2: "olfato" },
        { word: "boca", hint1: "Puede abrir puertas… o cerrarlas para siempre", hint2: "voz" },
        { word: "lengua", hint1: "Pequeña, pero capaz de meterte en líos", hint2: "sabor" },
        { word: "diente", hint1: "Resiste batallas diarias sin que lo notes", hint2: "morder" },
        { word: "oreja", hint1: "Recibe secretos que no siempre entiende", hint2: "eco" },
        { word: "cuello", hint1: "Une dos mundos y carga más de lo que parece", hint2: "soporte" },
        { word: "hombro", hint1: "Donde muchos descargan su peso emocional", hint2: "carga" },
        { word: "brazo", hint1: "Extensión que acerca lo que deseas", hint2: "alcance" },
        { word: "codo", hint1: "Se dobla cuando el camino lo exige", hint2: "ángulo" },
        { word: "mano", hint1: "Puede crear o destruir sin hablar", hint2: "tacto" },
        { word: "dedo", hint1: "Señala más de lo que debería", hint2: "punta" },
        { word: "uña", hint1: "Crece en silencio, pero deja marca", hint2: "rasguño" },
        { word: "pecho", hint1: "Protege lo que más importa", hint2: "latido" },
        { word: "espalda", hint1: "Sostiene todo… incluso lo que no ves", hint2: "soporte" },
        { word: "columna", hint1: "Estructura que decide si te mantienes firme", hint2: "eje" },
        { word: "abdomen", hint1: "Donde se siente lo que no se dice", hint2: "núcleo" },
        { word: "ombligo", hint1: "Recuerdo silencioso de un inicio", hint2: "centro" },
        { word: "cintura", hint1: "Divide sin separar del todo", hint2: "curva" },
        { word: "cadera", hint1: "Marca el ritmo sin hacer ruido", hint2: "balanceo" },
        { word: "pierna", hint1: "Te lleva lejos, aunque no siempre quieras", hint2: "paso" },
        { word: "rodilla", hint1: "Se rinde antes que el resto", hint2: "flexión" },
        { word: "tobillo", hint1: "Pequeño, pero crucial para avanzar", hint2: "equilibrio" },
        { word: "pie", hint1: "Siempre toca la realidad primero", hint2: "suelo" },
        { word: "talón", hint1: "Puede ser tu punto más débil", hint2: "vulnerable" },
        { word: "piel", hint1: "Cuenta historias sin palabras", hint2: "contacto" },
        { word: "frente", hint1: "Delata más de lo que quisieras ocultar", hint2: "gesto" },
        { word: "ceja", hint1: "Habla incluso cuando estás en silencio", hint2: "expresión" },
        { word: "pestaña", hint1: "Filtra lo que entra sin que lo notes", hint2: "parpadeo" },
        { word: "mejilla", hint1: "Recibe tanto cariño como vergüenza", hint2: "rubor" },
        { word: "labio", hint1: "Guarda palabras… o las libera", hint2: "susurro" },
        { word: "barbilla", hint1: "Pequeño punto de orgullo o duda", hint2: "perfil" },
        { word: "mandíbula", hint1: "Se tensa cuando algo no está bien", hint2: "presión" },
        { word: "costilla", hint1: "Protege sin ser vista", hint2: "arco" },
        { word: "pulmón", hint1: "Se llena y vacía sin pedir permiso", hint2: "aire" },
        { word: "corazón", hint1: "Late incluso cuando quieres ignorarlo", hint2: "ritmo" },
        { word: "hígado", hint1: "Trabaja en silencio tras excesos", hint2: "filtro" },
        { word: "estómago", hint1: "Reacciona antes que tu mente", hint2: "nudo" },
        { word: "intestino", hint1: "Proceso largo que pocos quieren pensar", hint2: "flujo" },
        { word: "riñón", hint1: "Decide qué se queda y qué se va", hint2: "depurar" },
        { word: "muslo", hint1: "Fuerza oculta en movimiento", hint2: "impulso" },
        { word: "pantorrilla", hint1: "Trabaja cuando subes… y cuando huyes", hint2: "tensión" },
        { word: "tendón", hint1: "Conecta fuerza con acción", hint2: "unión" },
        { word: "ligamento", hint1: "Mantiene todo en su sitio… hasta que falla", hint2: "soporte" },
        { word: "cráneo", hint1: "Caja cerrada con contenido valioso", hint2: "protección" },
        { word: "retina", hint1: "Donde todo se vuelve imagen", hint2: "luz" },
        { word: "iris", hint1: "Color que no siempre revela la verdad", hint2: "tono" },
        { word: "espinilla", hint1: "Recibe golpes que no olvidas", hint2: "dolor" },
        { word: "talón de aquiles", hint1: "Aquello que parece pequeño pero te derriba", hint2: "debilidad" }
    ],
    "Animales": [
        { word: "león", hint1: "No siempre necesita moverse para imponer respeto", hint2: "melena" },
        { word: "tigre", hint1: "Se acerca en silencio antes de decidirlo todo", hint2: "rayas" },
        { word: "elefante", hint1: "Recuerda más de lo que aparenta olvidar", hint2: "memoria" },
        { word: "jirafa", hint1: "Observa desde arriba sin involucrarse demasiado", hint2: "altura" },
        { word: "cebra", hint1: "Confunde más cuando está en grupo", hint2: "contraste" },
        { word: "caballo", hint1: "Corre como si algo lo persiguiera siempre", hint2: "galope" },
        { word: "perro", hint1: "Puede entenderte incluso cuando no hablas", hint2: "lealtad" },
        { word: "gato", hint1: "Se acerca cuando quiere… y se va cuando más lo notas", hint2: "independiente" },
        { word: "lobo", hint1: "Prefiere la compañía… pero solo de los suyos", hint2: "manada" },
        { word: "zorro", hint1: "Nunca es la primera opción… pero suele ganar", hint2: "astucia" },
        { word: "oso", hint1: "Puede parecer tranquilo hasta que lo interrumpes", hint2: "hibernar" },
        { word: "conejo", hint1: "Siempre parece listo para desaparecer", hint2: "salto" },
        { word: "ciervo", hint1: "Elegancia que huye antes de confirmar peligro", hint2: "huida" },
        { word: "rinoceronte", hint1: "No cambia de rumbo una vez decidido", hint2: "carga" },
        { word: "hipopótamo", hint1: "Tranquilo en apariencia… peligroso sin aviso", hint2: "agua" },
        { word: "cocodrilo", hint1: "Espera inmóvil hasta que ya es tarde", hint2: "emboscada" },
        { word: "serpiente", hint1: "Avanza sin hacer ruido ni mostrar intenciones", hint2: "veneno" },
        { word: "águila", hint1: "Ve oportunidades donde otros no miran", hint2: "altura" },
        { word: "búho", hint1: "Despierta cuando todo parece terminado", hint2: "noche" },
        { word: "halcón", hint1: "Decide rápido y no falla dos veces", hint2: "picada" },
        { word: "pingüino", hint1: "No vuela, pero no lo necesita para destacar", hint2: "frío" },
        { word: "delfín", hint1: "Juega como si entendiera más de lo que debería", hint2: "eco" },
        { word: "ballena", hint1: "Su presencia se siente aunque no la veas", hint2: "profundo" },
        { word: "tiburón", hint1: "Siempre está avanzando, incluso en calma", hint2: "aleta" },
        { word: "pulpo", hint1: "Tiene más soluciones de las que imaginas", hint2: "tentáculos" },
        { word: "medusa", hint1: "Hermosa a distancia, error al contacto", hint2: "flotar" },
        { word: "caballito de mar", hint1: "Rompe roles sin hacer ruido", hint2: "invertido" },
        { word: "hormiga", hint1: "Pequeña, pero nunca trabaja sola", hint2: "colonia" },
        { word: "abeja", hint1: "Produce más de lo que aparenta", hint2: "enjambre" },
        { word: "mariposa", hint1: "Su historia es más larga que su apariencia final", hint2: "metamorfosis" },
        { word: "araña", hint1: "Construye trampas sin perseguir directamente", hint2: "red" },
        { word: "escorpión", hint1: "No necesita tamaño para ser temido", hint2: "aguijón" },
        { word: "cangrejo", hint1: "Avanza sin ir directamente al punto", hint2: "lateral" },
        { word: "langosta", hint1: "Cambia completamente sin dejar de ser lo mismo", hint2: "muda" },
        { word: "pez globo", hint1: "Se vuelve algo que no parece cuando se siente en peligro", hint2: "inflar" },
        { word: "camaleón", hint1: "Se adapta tanto que desaparece sin irse", hint2: "color" },
        { word: "pavo real", hint1: "No pasa desapercibido aunque lo intente", hint2: "plumas" },
        { word: "gallina", hint1: "Se altera antes de que pase algo", hint2: "ruido" },
        { word: "gallo", hint1: "Anuncia sin preguntar si quieres escuchar", hint2: "amanecer" },
        { word: "cerdo", hint1: "Disfruta lo simple sin preocuparse por el qué dirán", hint2: "lodo" },
        { word: "vaca", hint1: "Produce más de lo que consume", hint2: "rumiar" },
        { word: "oveja", hint1: "Prefiere seguir antes que decidir", hint2: "rebaño" },
        { word: "cabra", hint1: "Llega donde otros ni lo intentan", hint2: "escalar" },
        { word: "murciélago", hint1: "Se orienta sin ver como tú esperas", hint2: "eco" },
        { word: "mapache", hint1: "Explora donde no debería, especialmente de noche", hint2: "curioso" },
        { word: "hurón", hint1: "Se mete en lugares donde otros no caben", hint2: "alargado" },
        { word: "koala", hint1: "Vive lento, pero con propósito claro", hint2: "eucalipto" },
        { word: "canguro", hint1: "Avanza dando saltos, no pasos", hint2: "bolsa" },
        { word: "panda", hint1: "Parece tierno, pero no es débil", hint2: "bambú" },
        { word: "lémur", hint1: "Observa con curiosidad constante", hint2: "cola" }
    ],
    "Emociones": [
        { word: "alegría", hint1: "Aparece sin permiso y cambia el ambiente", hint2: "brillo" },
        { word: "tristeza", hint1: "Se instala sin hacer ruido y pesa más con el tiempo", hint2: "caída" },
        { word: "enojo", hint1: "Explota cuando algo ya no se puede contener", hint2: "chispa" },
        { word: "miedo", hint1: "Te hace retroceder incluso sin pruebas claras", hint2: "sombra" },
        { word: "sorpresa", hint1: "Rompe lo esperado en un instante", hint2: "giro" },
        { word: "asco", hint1: "Rechazo inmediato sin necesidad de explicación", hint2: "repulsión" },
        { word: "amor", hint1: "Puede construir o destruir dependiendo del momento", hint2: "vínculo" },
        { word: "odio", hint1: "Se alimenta incluso sin presencia constante", hint2: "rechazo" },
        { word: "ansiedad", hint1: "Corre más rápido que el presente", hint2: "anticipar" },
        { word: "calma", hint1: "Todo sigue igual, pero sin ruido interno", hint2: "quietud" },
        { word: "culpa", hint1: "Permanece aunque nadie más lo recuerde", hint2: "peso" },
        { word: "vergüenza", hint1: "Hace que quieras desaparecer sin moverte", hint2: "rubor" },
        { word: "orgullo", hint1: "Puede levantarte… o impedirte bajar", hint2: "altura" },
        { word: "celos", hint1: "Aparece cuando comparas lo que no deberías", hint2: "posesión" },
        { word: "envidia", hint1: "Desea lo ajeno sin admitirlo", hint2: "comparar" },
        { word: "gratitud", hint1: "Reconoce lo recibido sin obligación", hint2: "agradecer" },
        { word: "esperanza", hint1: "Sigue presente incluso cuando todo falla", hint2: "futuro" },
        { word: "desesperación", hint1: "Cuando ya no ves salida aunque exista", hint2: "límite" },
        { word: "confianza", hint1: "Se entrega antes de comprobar todo", hint2: "fe" },
        { word: "desconfianza", hint1: "Duda incluso cuando no hay señales claras", hint2: "sospecha" },
        { word: "admiración", hint1: "Miras hacia arriba sin sentirte menos", hint2: "respeto" },
        { word: "desprecio", hint1: "Miras hacia abajo sin decirlo", hint2: "rechazo" },
        { word: "nostalgia", hint1: "Extraña algo que ya no es igual", hint2: "recuerdo" },
        { word: "melancolía", hint1: "Tristeza suave que no se va del todo", hint2: "gris" },
        { word: "alivio", hint1: "Llega cuando algo deja de presionar", hint2: "soltar" },
        { word: "tensión", hint1: "Todo parece a punto de romperse", hint2: "cuerda" },
        { word: "placer", hint1: "Se busca aunque dure poco", hint2: "disfrute" },
        { word: "aburrimiento", hint1: "Nada parece suficiente para interesarte", hint2: "vacío" },
        { word: "curiosidad", hint1: "Te empuja a saber incluso sin necesidad", hint2: "pregunta" },
        { word: "confusión", hint1: "Muchas opciones, ninguna clara", hint2: "niebla" },
        { word: "determinación", hint1: "Avanza aunque todo diga lo contrario", hint2: "firmeza" },
        { word: "frustración", hint1: "Intentas y no cambia nada", hint2: "bloqueo" },
        { word: "soledad", hint1: "No depende de cuántos estén cerca", hint2: "vacío" },
        { word: "compasión", hint1: "Sientes el dolor ajeno como propio", hint2: "empatía" },
        { word: "empatía", hint1: "Entiendes sin vivir lo mismo exactamente", hint2: "conectar" },
        { word: "ira", hint1: "Más intensa que el enojo, menos controlable", hint2: "furia" },
        { word: "ternura", hint1: "Aparece frente a lo frágil o delicado", hint2: "suave" },
        { word: "timidez", hint1: "Te frena antes de empezar", hint2: "oculto" },
        { word: "seguridad", hint1: "No necesitas demostrar nada", hint2: "certeza" },
        { word: "inseguridad", hint1: "Dudas incluso de lo que sabes", hint2: "duda" },
        { word: "euforia", hint1: "Sube tanto que cuesta mantenerlo", hint2: "alto" },
        { word: "apatía", hint1: "Nada importa lo suficiente", hint2: "indiferente" },
        { word: "remordimiento", hint1: "Regresa después de que ya pasó todo", hint2: "error" },
        { word: "ilusión", hint1: "Se construye antes de saber si es real", hint2: "expectativa" },
        { word: "decepción", hint1: "Cuando la realidad no alcanza lo esperado", hint2: "caída" },
        { word: "motivación", hint1: "Empieza el movimiento sin obligación externa", hint2: "impulso" },
        { word: "agotamiento", hint1: "Ya no queda energía ni para intentarlo", hint2: "límite" },
        { word: "satisfacción", hint1: "Sensación de cierre tras lograr algo", hint2: "cumplido" },
        { word: "ansia", hint1: "Deseo intenso que no espera turno", hint2: "urgencia" },
        { word: "vergüenza ajena", hint1: "La sientes por alguien que ni sabe que la merece", hint2: "cringe" }
    ],
    "Comida": [
        { word: "ceviche", hint1: "No necesita fuego para volverse inolvidable", hint2: "ácido" },
        { word: "lomo saltado", hint1: "Cruza fronteras sin dejar de ser local", hint2: "saltear" },
        { word: "aji de gallina", hint1: "Suave en apariencia, intenso en fondo", hint2: "cremoso" },
        { word: "causa", hint1: "Capas que esconden historia y sabor", hint2: "amarillo" },
        { word: "anticuchos", hint1: "Lo que muchos dudan… termina encantando", hint2: "brasa" },
        { word: "papa a la huancaina", hint1: "Frío por fuera, potente por dentro", hint2: "salsa" },
        { word: "arroz con pollo", hint1: "Color que no pasa desapercibido en mesa", hint2: "verde" },
        { word: "seco de carne", hint1: "No es seco, pero el nombre insiste", hint2: "cilantro" },
        { word: "tacu tacu", hint1: "Reutiliza y termina superando el original", hint2: "mezcla" },
        { word: "chaufa", hint1: "No nació aquí, pero se quedó para siempre", hint2: "wok" },
        { word: "parihuela", hint1: "Dicen que revive más que alimenta", hint2: "mar" },
        { word: "juane", hint1: "Envuelto como secreto que vale la pena abrir", hint2: "hoja" },
        { word: "pachamanca", hint1: "Se cocina donde no esperarías", hint2: "tierra" },
        { word: "rocoto relleno", hint1: "Advertencia clara que muchos ignoran", hint2: "fuego" },
        { word: "adobo arequipeño", hint1: "Empieza fuerte incluso antes del día", hint2: "madrugar" },
        { word: "carapulcra", hint1: "Antiguo y persistente en el tiempo", hint2: "seco" },
        { word: "olluquito con carne", hint1: "Pequeño ingrediente, gran presencia", hint2: "amarillo" },
        { word: "cabrito norteño", hint1: "Lento proceso, resultado firme", hint2: "chicha" },
        { word: "arroz con mariscos", hint1: "El mar mezclado sin orden aparente", hint2: "naranja" },
        { word: "sopa seca", hint1: "Contradicción que sí funciona", hint2: "espeso" },
        { word: "tallarines verdes", hint1: "Color poco común para algo tan casero", hint2: "hierba" },
        { word: "pollo a la brasa", hint1: "Ritual colectivo disfrazado de comida", hint2: "rotar" },
        { word: "chicharron", hint1: "Cruje antes de convencerte", hint2: "grasa" },
        { word: "tamales", hint1: "Paciencia antes de descubrir", hint2: "vapor" },
        { word: "empanadas", hint1: "Nada revela lo que guarda hasta el final", hint2: "horno" },
        { word: "salchipapas", hint1: "Simple, rápido y difícil de dejar", hint2: "mezcla" },
        { word: "hamburguesa", hint1: "Capas que intentan sostenerse juntas", hint2: "apilar" },
        { word: "pizza", hint1: "Siempre falta una parte, incluso completa", hint2: "triángulo" },
        { word: "lasagna", hint1: "Orden en capas que se desarma al final", hint2: "hornear" },
        { word: "spaghetti", hint1: "Se enreda más cuanto más intentas controlarlo", hint2: "largo" },
        { word: "ramen", hint1: "Caliente, profundo y lleno de detalles", hint2: "caldo" },
        { word: "hot dog", hint1: "Se sostiene apenas mientras lo comes", hint2: "pan" },
        { word: "broaster", hint1: "Crujiente por fuera, distinto por dentro", hint2: "freír" },
        { word: "alitas", hint1: "Pequeñas, pero dejan huella", hint2: "salsa" },
        { word: "costillas", hint1: "Se separa solo cuando está listo", hint2: "hueso" },
        { word: "paella", hint1: "Todo junto sin perder identidad", hint2: "azafrán" },
        { word: "risotto", hint1: "Textura que depende del momento exacto", hint2: "cremoso" },
        { word: "curry", hint1: "Aroma que llega antes que el sabor", hint2: "especias" },
        { word: "burrito", hint1: "Envuelve más de lo que aparenta", hint2: "rollo" },
        { word: "nachos", hint1: "Desorden que funciona mejor compartido", hint2: "crujir" },
        { word: "falafel", hint1: "Pequeño, frito y lleno de historia", hint2: "garbanzo" },
        { word: "shawarma", hint1: "Gira antes de llegar a ti", hint2: "corte" },
        { word: "dumplings", hint1: "Cerrados, pero no completamente ocultos", hint2: "vapor" },
        { word: "sushi", hint1: "Precisión en cada pieza", hint2: "rollo" },
        { word: "poke", hint1: "Ordenado pero sin cocinar", hint2: "crudo" },
        { word: "tortilla", hint1: "Base que cambia según quién la use", hint2: "plano" },
        { word: "pan con pollo", hint1: "Clásico que no necesita presentación", hint2: "relleno" },
        { word: "butifarra", hint1: "Sencillo, pero con identidad marcada", hint2: "jamón" },
        { word: "triple", hint1: "Más capas, más decisiones", hint2: "niveles" },
        { word: "leche de tigre", hint1: "Lo que queda después de la fiesta principal… y es lo mejor", hint2: "resaca" }
    ],
    "Videojuegos": [
        { word: "Super Mario Bros", hint1: "Empieza simple, pero no todo es avanzar a la derecha", hint2: "tubería" },
        { word: "The Legend of Zelda", hint1: "Explorar importa tanto como pelear", hint2: "reliquia" },
        { word: "Minecraft", hint1: "El límite no está en el juego, sino en quien lo juega", hint2: "bloques" },
        { word: "Fortnite", hint1: "Empieza con muchos, termina con uno", hint2: "tormenta" },
        { word: "Call of Duty", hint1: "Reflejos rápidos marcan la diferencia", hint2: "disparo" },
        { word: "Grand Theft Auto V", hint1: "Libertad total… con consecuencias opcionales", hint2: "ciudad" },
        { word: "Red Dead Redemption 2", hint1: "Lento, detallado y sin prisa por terminar", hint2: "oeste" },
        { word: "The Witcher 3", hint1: "Decidir mal también es una decisión válida", hint2: "contrato" },
        { word: "Dark Souls", hint1: "Fracasar es parte del progreso", hint2: "hoguera" },
        { word: "Elden Ring", hint1: "No te guía, te deja aprender a golpes", hint2: "anillo" },
        { word: "League of Legends", hint1: "El error de uno afecta a todos", hint2: "líneas" },
        { word: "Dota 2", hint1: "Estrategia profunda, caos constante", hint2: "ancestro" },
        { word: "Counter-Strike", hint1: "Un segundo decide todo", hint2: "bomba" },
        { word: "Valorant", hint1: "Precisión con un toque diferente", hint2: "habilidad" },
        { word: "Overwatch", hint1: "No basta con apuntar bien", hint2: "equipo" },
        { word: "Among Us", hint1: "La verdad no siempre gana", hint2: "impostor" },
        { word: "Roblox", hint1: "No es uno, son miles dentro", hint2: "crear" },
        { word: "Terraria", hint1: "Más profundo de lo que parece al inicio", hint2: "excavar" },
        { word: "Stardew Valley", hint1: "Avanzas sin prisa, pero no sin decisiones", hint2: "granja" },
        { word: "The Sims", hint1: "Controlas vidas… pero no todo", hint2: "simular" },
        { word: "FIFA", hint1: "Siempre hay una revancha pendiente", hint2: "gol" },
        { word: "PES", hint1: "Menos brillo, más control", hint2: "cancha" },
        { word: "God of War", hint1: "Fuerza con historia detrás", hint2: "mitología" },
        { word: "Halo", hint1: "No estás solo en el campo, pero lo parece", hint2: "espacio" },
        { word: "DOOM", hint1: "Avanzar significa no detenerse nunca", hint2: "demonios" },
        { word: "Resident Evil", hint1: "Cada recurso cuenta más de lo que crees", hint2: "infectado" },
        { word: "Silent Hill", hint1: "El miedo no siempre es externo", hint2: "niebla" },
        { word: "Five Nights at Freddy's", hint1: "Mirar demasiado también es peligroso", hint2: "cámaras" },
        { word: "Metal Gear Solid", hint1: "Evitar es mejor que enfrentar", hint2: "sigilo" },
        { word: "Assassin's Creed", hint1: "El pasado nunca está realmente atrás", hint2: "salto" },
        { word: "Cyberpunk 2077", hint1: "Futuro brillante con grietas profundas", hint2: "implantes" },
        { word: "Half-Life", hint1: "No necesitas hablar para avanzar", hint2: "científico" },
        { word: "Portal", hint1: "La solución no siempre está frente a ti", hint2: "portales" },
        { word: "Left 4 Dead", hint1: "Sobrevivir solo no es opción", hint2: "horda" },
        { word: "Dead by Daylight", hint1: "Correr no siempre es suficiente", hint2: "gancho" },
        { word: "Clash of Clans", hint1: "Construyes mientras otros planean destruir", hint2: "aldea" },
        { word: "Clash Royale", hint1: "Cada decisión cuesta en tiempo real", hint2: "cartas" },
        { word: "Brawl Stars", hint1: "Rápido, caótico y sin pausas largas", hint2: "arena" },
        { word: "Geometry Dash", hint1: "El error se paga al instante", hint2: "ritmo" },
        { word: "Undertale", hint1: "Pelear no siempre es necesario", hint2: "decidir" },
        { word: "Hollow Knight", hint1: "Pequeño, pero el mundo no lo es", hint2: "insecto" },
        { word: "Cuphead", hint1: "Parece antiguo… no lo es en dificultad", hint2: "dibujos" },
        { word: "Celeste", hint1: "Subir es más difícil que caer", hint2: "montaña" },
        { word: "Fall Guys", hint1: "Competir nunca fue tan torpe", hint2: "caer" },
        { word: "Subnautica", hint1: "Lo desconocido está debajo, no arriba", hint2: "océano" },
        { word: "ARK Survival Evolved", hint1: "Sobrevivir implica domesticar lo imposible", hint2: "dinosaurios" },
        { word: "The Forest", hint1: "No todo lo que ves es lo peor", hint2: "isla" },
        { word: "Phasmophobia", hint1: "Hablar puede empeorar todo", hint2: "fantasma" },
        { word: "Skyrim", hint1: "Tu camino depende más de ti que del destino", hint2: "dragón" },
        { word: "Fallout", hint1: "El mundo ya terminó… pero sigues aquí", hint2: "yermo" }
    ],
    "Superhéroes": [
        { word: "Batman", hint1: "No necesita poderes para dar miedo", hint2: "murciélago" },
        { word: "Superman", hint1: "Demasiado perfecto… excepto por un detalle", hint2: "criptonita" },
        { word: "Spider-Man", hint1: "Se balancea entre responsabilidad y caos", hint2: "telaraña" },
        { word: "Iron Man", hint1: "Más mente que músculo, pero igual de peligroso", hint2: "armadura" },
        { word: "Captain America", hint1: "Viejos valores en tiempos nuevos", hint2: "escudo" },
        { word: "Thor", hint1: "El poder cae desde arriba", hint2: "martillo" },
        { word: "Hulk", hint1: "Cuanto peor se pone todo, más fuerte responde", hint2: "ira" },
        { word: "Black Widow", hint1: "El pasado pesa más que sus movimientos", hint2: "espía" },
        { word: "Hawkeye", hint1: "No falla cuando ya decidió", hint2: "flecha" },
        { word: "Doctor Strange", hint1: "Lo imposible es solo cuestión de perspectiva", hint2: "hechizo" },
        { word: "Scarlet Witch", hint1: "La realidad no siempre es fija", hint2: "caos" },
        { word: "Vision", hint1: "Existe entre lo tangible y lo imposible", hint2: "sintético" },
        { word: "Black Panther", hint1: "Protege más que solo territorio", hint2: "vibranio" },
        { word: "Ant-Man", hint1: "Menos tamaño, más posibilidades", hint2: "encoger" },
        { word: "Wasp", hint1: "Pequeña, rápida y difícil de seguir", hint2: "alas" },
        { word: "Captain Marvel", hint1: "Energía sin límites claros", hint2: "cósmico" },
        { word: "Deadpool", hint1: "Rompe más que reglas", hint2: "cuarta" },
        { word: "Wolverine", hint1: "Se recupera antes de terminar la pelea", hint2: "garras" },
        { word: "Professor X", hint1: "Lidera sin levantarse", hint2: "mente" },
        { word: "Magneto", hint1: "Controla lo que otros ignoran", hint2: "metal" },
        { word: "Flash", hint1: "Siempre llega antes… o demasiado tarde", hint2: "velocidad" },
        { word: "Wonder Woman", hint1: "Fuerza y verdad en equilibrio", hint2: "lazo" },
        { word: "Aquaman", hint1: "Gobierna donde otros no respiran", hint2: "océano" },
        { word: "Green Lantern", hint1: "Imagina y se vuelve real", hint2: "anillo" },
        { word: "Cyborg", hint1: "Mitad decisión, mitad programación", hint2: "tecnología" },
        { word: "Shazam", hint1: "Una palabra lo cambia todo", hint2: "rayo" },
        { word: "Joker", hint1: "El caos también puede sonreír", hint2: "risa" },
        { word: "Harley Quinn", hint1: "Locura con lealtad impredecible", hint2: "mazo" },
        { word: "Lex Luthor", hint1: "No necesita fuerza para enfrentarlo", hint2: "genio" },
        { word: "Thanos", hint1: "Equilibrio llevado al extremo", hint2: "guante" },
        { word: "Loki", hint1: "Nunca sabes si dice la verdad", hint2: "engaño" },
        { word: "Ultron", hint1: "La lógica sin límites humanos", hint2: "IA" },
        { word: "Green Goblin", hint1: "Ataca desde donde no lo esperas", hint2: "planeador" },
        { word: "Doctor Octopus", hint1: "Más brazos, más problemas", hint2: "tentáculos" },
        { word: "Venom", hint1: "No está solo dentro de sí", hint2: "simbionte" },
        { word: "Carnage", hint1: "Más descontrol, menos reglas", hint2: "caos" },
        { word: "Riddler", hint1: "Te da la respuesta… si la encuentras", hint2: "acertijo" },
        { word: "Penguin", hint1: "No necesita fuerza para dominar", hint2: "mafioso" },
        { word: "Two-Face", hint1: "Decide sin decidir realmente", hint2: "moneda" },
        { word: "Bane", hint1: "Rompe más que solo planes", hint2: "fuerza" },
        { word: "Catwoman", hint1: "Nunca está del todo de un lado", hint2: "sigilo" },
        { word: "Daredevil", hint1: "Ve sin ver", hint2: "sentidos" },
        { word: "Punisher", hint1: "No cree en segundas oportunidades", hint2: "castigo" },
        { word: "Ghost Rider", hint1: "El juicio llega ardiendo", hint2: "llamas" },
        { word: "Blade", hint1: "Caza lo que se oculta en la noche", hint2: "vampiro" },
        { word: "Storm", hint1: "El clima responde a su estado", hint2: "tormenta" },
        { word: "Jean Grey", hint1: "Poder que puede perder el control", hint2: "fénix" },
        { word: "Nightwing", hint1: "Sale de una sombra para crear la suya", hint2: "acróbata" },
        { word: "Robin", hint1: "Aprendió bajo alguien que no confía en nadie", hint2: "aprendiz" },
        { word: "Moon Knight", hint1: "Ni él mismo siempre sabe quién es", hint2: "luna" }
    ],
    "Famosos": [
        { word: "Michael Jackson", hint1: "Reinó en su género con pasos que nadie pudo copiar del todo", hint2: "moonwalk" },
        { word: "Madonna", hint1: "Cambió tantas veces que nunca dejó de ser tendencia", hint2: "reinventar" },
        { word: "Elvis Presley", hint1: "Movimientos que en su tiempo fueron demasiado", hint2: "rey" },
        { word: "Freddie Mercury", hint1: "Voz imposible de ignorar, presencia imposible de olvidar", hint2: "bigote" },
        { word: "Shakira", hint1: "Lo que hace con el cuerpo también comunica", hint2: "caderas" },
        { word: "Bad Bunny", hint1: "Rompe reglas sin pedir permiso", hint2: "conejo" },
        { word: "Taylor Swift", hint1: "Convierte experiencias en historias que millones repiten", hint2: "eras" },
        { word: "Drake", hint1: "Siempre presente aunque cambie el estilo", hint2: "canadá" },
        { word: "Rihanna", hint1: "No necesita lanzar seguido para seguir dominando", hint2: "diamantes" },
        { word: "Beyoncé", hint1: "Control absoluto en escenario y fuera de él", hint2: "queen" },
        { word: "Cristiano Ronaldo", hint1: "Disciplina que se volvió marca personal", hint2: "siu" },
        { word: "Lionel Messi", hint1: "Hace parecer fácil lo que no lo es", hint2: "zurdo" },
        { word: "Neymar", hint1: "Talento y espectáculo en cada movimiento", hint2: "drible" },
        { word: "LeBron James", hint1: "Constancia que supera generaciones", hint2: "rey" },
        { word: "Michael Jordan", hint1: "Definió la excelencia en su disciplina", hint2: "23" },
        { word: "Dwayne Johnson", hint1: "Pasó de fuerza física a presencia global", hint2: "roca" },
        { word: "Keanu Reeves", hint1: "Fama sin perder sencillez", hint2: "matrix" },
        { word: "Johnny Depp", hint1: "Se transforma más de lo que actúa", hint2: "pirata" },
        { word: "Leonardo DiCaprio", hint1: "Tardó en llegar… pero cuando llegó, todos lo notaron", hint2: "oscar" },
        { word: "Tom Cruise", hint1: "No necesita dobles para impresionar", hint2: "misión" },
        { word: "Will Smith", hint1: "Carisma que atraviesa generaciones", hint2: "príncipe" },
        { word: "Robert Downey Jr", hint1: "Resurgió cuando parecía terminado", hint2: "armadura" },
        { word: "Scarlett Johansson", hint1: "Presencia fuerte sin necesidad de exagerar", hint2: "viuda" },
        { word: "Emma Watson", hint1: "Creció frente a todos sin desaparecer después", hint2: "magia" },
        { word: "Daniel Radcliffe", hint1: "Siempre será asociado a algo que no puede soltar", hint2: "cicatriz" },
        { word: "Dua Lipa", hint1: "Ritmo moderno con estética clara", hint2: "dance" },
        { word: "Billie Eilish", hint1: "Rompe moldes con tono bajo y estilo propio", hint2: "verde" },
        { word: "Ariana Grande", hint1: "Voz potente en apariencia ligera", hint2: "alto" },
        { word: "Justin Bieber", hint1: "Pasó de fenómeno juvenil a constante global", hint2: "baby" },
        { word: "Ed Sheeran", hint1: "Minimalismo que llena estadios", hint2: "guitarra" },
        { word: "Gianluca Lapadula", hint1: "Llegó de fuera, pero terminó siendo clave dentro", hint2: "gol" },
        { word: "Paolo Guerrero", hint1: "Referencia constante cuando se habla de ataque", hint2: "capitán" },
        { word: "Jefferson Farfán", hint1: "Velocidad que marcó una época", hint2: "foquita" },
        { word: "Claudio Pizarro", hint1: "Triunfó más afuera que dentro", hint2: "bombardero" },
        { word: "Pedro Suárez Vértiz", hint1: "Sus canciones siguen aunque él ya no esté", hint2: "voz" },
        { word: "Gian Marco", hint1: "Más reconocido por lo que escribe que por lo que canta", hint2: "autor" },
        { word: "Yahaira Plasencia", hint1: "Ritmo y polémica en partes iguales", hint2: "salsa" },
        { word: "Magaly Medina", hint1: "Muchos la temen cuando habla", hint2: "ampay" },
        { word: "Laura Bozzo", hint1: "El drama siempre escala cuando aparece", hint2: "pase" },
        { word: "Carlos Alcántara", hint1: "Humor que se volvió cine", hint2: "macho" },
        { word: "Andrés Wiese", hint1: "Fama ligada a una historia larga en pantalla", hint2: "serie" },
        { word: "Nicolás Galindo", hint1: "Figura joven asociada a contenido digital", hint2: "stream" },
        { word: "Bruno Pinasco", hint1: "Siempre cerca del entretenimiento y novedades", hint2: "cine" },
        { word: "Raúl Romero", hint1: "Energía caótica que marcó generaciones", hint2: "show" },
        { word: "Gisela Valcárcel", hint1: "Presencia constante en la televisión local", hint2: "conductora" },
        { word: "Tilsa Lozano", hint1: "Fama ligada tanto a medios como a polémicas", hint2: "modelo" },
        { word: "Natalie Vértiz", hint1: "Elegancia que migró de pasarela a pantalla", hint2: "reina" },
        { word: "Sheyla Rojas", hint1: "Siempre en el ojo público, por distintas razones", hint2: "escándalo" },
        { word: "Maju Mantilla", hint1: "Reconocimiento que empezó con una corona", hint2: "belleza" },
        { word: "Ricardo Gareca", hint1: "No nació aquí, pero cambió todo aquí", hint2: "tigre" }
    ],
    "Países": [
        { word: "Perú", hint1: "Tiene más de un mundo dentro de sus fronteras", hint2: "andes" },
        { word: "Estados Unidos", hint1: "Influye en todo, incluso fuera de su territorio", hint2: "potencia" },
        { word: "Brasil", hint1: "Grande en tamaño y en ruido cultural", hint2: "samba" },
        { word: "Argentina", hint1: "Orgullo que se siente incluso al hablar", hint2: "mate" },
        { word: "México", hint1: "Color, historia y sabor que cruzan fronteras", hint2: "azteca" },
        { word: "España", hint1: "Dejó huella en lugares donde nunca estuvo físicamente", hint2: "castilla" },
        { word: "Francia", hint1: "Elegancia que también sabe protestar", hint2: "torre" },
        { word: "Italia", hint1: "Donde el pasado compite con el presente", hint2: "roma" },
        { word: "Alemania", hint1: "Precisión que define su identidad moderna", hint2: "ingeniería" },
        { word: "Reino Unido", hint1: "Tradición que no siempre sigue reglas actuales", hint2: "corona" },
        { word: "Japón", hint1: "Futuro y tradición coexistiendo sin problema", hint2: "isla" },
        { word: "China", hint1: "Antiguo y masivo, pero siempre en movimiento", hint2: "dragón" },
        { word: "Corea del Sur", hint1: "Pequeño territorio con gran impacto global reciente", hint2: "kpop" },
        { word: "India", hint1: "Diversidad difícil de resumir en una sola idea", hint2: "hindu" },
        { word: "Rusia", hint1: "Extensión enorme, decisiones igual de grandes", hint2: "frío" },
        { word: "Canadá", hint1: "Tranquilo en apariencia, gigante en extensión", hint2: "norte" },
        { word: "Australia", hint1: "Lejos de casi todo, pero único en todo", hint2: "canguros" },
        { word: "Chile", hint1: "Largo más que ancho, extremo en geografía", hint2: "cordillera" },
        { word: "Colombia", hint1: "Energía cultural que se siente en su música", hint2: "café" },
        { word: "Ecuador", hint1: "Su nombre dice más de lo que parece", hint2: "línea" },
        { word: "Bolivia", hint1: "Altura que se siente incluso al respirar", hint2: "altiplano" },
        { word: "Venezuela", hint1: "Riqueza natural en contraste con su situación", hint2: "petróleo" },
        { word: "Uruguay", hint1: "Pequeño, pero firme en identidad", hint2: "mate" },
        { word: "Paraguay", hint1: "Poco mencionado, pero con historia propia", hint2: "guaraní" },
        { word: "Panamá", hint1: "Une más de lo que separa", hint2: "canal" },
        { word: "Costa Rica", hint1: "Prefiere conservar antes que explotar", hint2: "naturaleza" },
        { word: "Cuba", hint1: "Tiempo detenido en algunos aspectos", hint2: "revolución" },
        { word: "República Dominicana", hint1: "Comparte isla, pero no historia", hint2: "caribe" },
        { word: "Egipto", hint1: "Su pasado pesa más que su presente", hint2: "pirámides" },
        { word: "Sudáfrica", hint1: "Diversidad marcada por su historia reciente", hint2: "apartheid" },
        { word: "Marruecos", hint1: "Puerta entre dos mundos distintos", hint2: "desierto" },
        { word: "Turquía", hint1: "Ni completamente de un lado ni del otro", hint2: "puente" },
        { word: "Arabia Saudita", hint1: "Riqueza construida sobre un recurso clave", hint2: "petróleo" },
        { word: "Israel", hint1: "Historia antigua en conflicto moderno", hint2: "medio" },
        { word: "Grecia", hint1: "Ideas antiguas que aún influyen hoy", hint2: "filosofía" },
        { word: "Países Bajos", hint1: "Gana terreno donde no lo había", hint2: "diques" },
        { word: "Suecia", hint1: "Equilibrio social como modelo", hint2: "nórdico" },
        { word: "Noruega", hint1: "Riqueza sin perder conexión natural", hint2: "fiordos" },
        { word: "Finlandia", hint1: "Silencio y eficiencia combinados", hint2: "sauna" },
        { word: "Dinamarca", hint1: "Pequeño, pero influyente en bienestar", hint2: "vikingo" },
        { word: "Suiza", hint1: "Neutral incluso cuando otros no lo son", hint2: "bancos" },
        { word: "Austria", hint1: "Elegancia con historia imperial", hint2: "viena" },
        { word: "Bélgica", hint1: "Centro sin ser el más grande", hint2: "bruselas" },
        { word: "Portugal", hint1: "Miró al mar antes que muchos", hint2: "explorar" },
        { word: "Irlanda", hint1: "Verde que define su imagen", hint2: "trébol" },
        { word: "Nueva Zelanda", hint1: "Aislado, pero visualmente reconocido", hint2: "hobbit" },
        { word: "Filipinas", hint1: "Fragmentado geográficamente, unido culturalmente", hint2: "islas" },
        { word: "Indonesia", hint1: "Extenso, pero no continuo", hint2: "archipiélago" },
        { word: "Tailandia", hint1: "Turismo que mezcla tradición y modernidad", hint2: "templos" },
        { word: "Vietnam", hint1: "Historia marcada por conflictos pasados", hint2: "guerra" }
    ],
    "Abstracto": [
        { word: "Libertad", hint1: "Solo se nota realmente cuando deja de estar", hint2: "elección" },
        { word: "Tiempo", hint1: "Siempre avanza, aunque tú no lo hagas", hint2: "irreversible" },
        { word: "Verdad", hint1: "No cambia, pero sí la forma en que la aceptas", hint2: "absoluto" },
        { word: "Justicia", hint1: "Intenta equilibrar algo que nunca lo está", hint2: "balanza" },
        { word: "Destino", hint1: "Excusa para algunos, certeza para otros", hint2: "trazado" },
        { word: "Belleza", hint1: "Existe más en la percepción que en la realidad", hint2: "subjetivo" },
        { word: "Silencio", hint1: "Puede decir más que cualquier palabra", hint2: "ausencia" },
        { word: "Caos", hint1: "Donde todo parece roto… pero no lo está del todo", hint2: "desorden" },
        { word: "Ilusión", hint1: "Se siente real hasta que deja de serlo", hint2: "engaño" },
        { word: "Karma", hint1: "No siempre llega rápido, pero rara vez se olvida", hint2: "retorno" },
        { word: "Conciencia", hint1: "Te observa incluso cuando nadie más lo hace", hint2: "juicio" },
        { word: "Infinito", hint1: "Nunca termina, aunque lo intentes medir", hint2: "eterno" },
        { word: "Paz", hint1: "No es ausencia de ruido, sino de conflicto", hint2: "calma" },
        { word: "Poder", hint1: "Cambia a quien lo tiene más que a quien lo sufre", hint2: "control" },
        { word: "Miedo", hint1: "Aparece antes que el peligro real", hint2: "instinto" },
        { word: "Esperanza", hint1: "Persiste incluso cuando no hay evidencia", hint2: "futuro" },
        { word: "Fe", hint1: "Creer sin necesitar pruebas visibles", hint2: "creencia" },
        { word: "Realidad", hint1: "No siempre coincide con lo que percibes", hint2: "hecho" },
        { word: "Sueño", hint1: "Puede sentirse más real que estar despierto", hint2: "irreal" },
        { word: "Memoria", hint1: "Cambia con el tiempo, aunque diga lo contrario", hint2: "recuerdo" },
        { word: "Olvido", hint1: "No siempre es voluntario", hint2: "vacío" },
        { word: "Identidad", hint1: "Se construye… pero también se pierde", hint2: "yo" },
        { word: "Existencia", hint1: "La única condición que no puedes negar del todo", hint2: "ser" },
        { word: "Vacío", hint1: "No tiene nada, pero puede sentirse pesado", hint2: "nada" },
        { word: "Equilibrio", hint1: "Difícil de mantener, fácil de romper", hint2: "balance" },
        { word: "Dualidad", hint1: "Dos opuestos que no pueden separarse", hint2: "contraste" },
        { word: "Eternidad", hint1: "Más allá de cualquier medida humana", hint2: "tiempo" },
        { word: "Destino", hint1: "Camino que algunos creen ya escrito", hint2: "inevitable" },
        { word: "Azar", hint1: "Cuando todo ocurre sin un patrón claro", hint2: "casualidad" },
        { word: "Orden", hint1: "Da sentido a lo que sin él sería caos", hint2: "estructura" },
        { word: "Control", hint1: "Ilusión que se pierde fácilmente", hint2: "dominio" },
        { word: "Deseo", hint1: "Empuja incluso cuando no deberías avanzar", hint2: "anhelo" },
        { word: "Voluntad", hint1: "Fuerza que no depende del cuerpo", hint2: "decisión" },
        { word: "Destino", hint1: "Se usa para justificar lo que no entiendes", hint2: "final" },
        { word: "Cambio", hint1: "Lo único constante aunque lo rechaces", hint2: "transformar" },
        { word: "Esencia", hint1: "Lo que queda cuando todo lo demás se va", hint2: "núcleo" },
        { word: "Percepción", hint1: "Define más que la realidad misma", hint2: "interpretar" },
        { word: "Conocimiento", hint1: "Cuanto más tienes, más dudas aparecen", hint2: "saber" },
        { word: "Ignorancia", hint1: "A veces protege más de lo que perjudica", hint2: "desconocer" },
        { word: "Libertad", hint1: "Muchos la buscan sin saber usarla", hint2: "decidir" },
        { word: "Responsabilidad", hint1: "Llega justo después de elegir", hint2: "carga" },
        { word: "Intención", hint1: "Importa más de lo que se ve", hint2: "motivo" },
        { word: "Realidad", hint1: "Puede romper cualquier ilusión", hint2: "verdad" },
        { word: "Tiempo", hint1: "Hace valioso todo lo que limita", hint2: "pasar" },
        { word: "Destino", hint1: "Se debate entre elección y obligación", hint2: "camino" },
        { word: "Existencia", hint1: "Pregunta sin respuesta definitiva", hint2: "vida" },
        { word: "Nada", hint1: "Concepto imposible de imaginar completamente", hint2: "vacío" },
        { word: "Todo", hint1: "Incluye incluso lo que no entiendes", hint2: "total" },
        { word: "Origen", hint1: "El punto que siempre quieres rastrear", hint2: "inicio" },
        { word: "Final", hint1: "Da sentido a todo lo anterior", hint2: "cierre" }
    ]
};